In [2]:
import numpy as np

### Multidimensional Array

Um array multidimensional é essencialmente, composto de listas de listas

In [39]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                 [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                 [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])
print(array.shape)

(3, 3, 3)

> Para acessar os valores dentro dos arrays, podemos utilizar `chain indexing` ou `multidimensional indexing` através do NumPy, que é significativamente mais rápido.

In [40]:
print(array[0][0][0]) # Chain indexing
print(array[0, 0, 0]) # Multidimensional indexing


nome = array[0, 0, 1] + array[1, 2, 2] + array[2, 0, 2] + array[1, 1, 1] + array[1, 1, 2] + array[2,2,2] + array[2, 0, 0]
print(nome)

A
A
BRUNO S

### Slicing

In [ ]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# print(array.ndim)
# print(array.shape)

# array[start:end:step]

# Selecionando linhas
print(array[0:4:2]) # end index é exclusivo, sempre indicar um index acima do que for exibido
print(array[::2])
print(array[::-1])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

In [66]:
# Selecionando colunas
print(array[:,2])

print(array[:,2:4])

print(array[2,2:4])

[ 3  7 11 15]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[11 12]

### Aritmética
#### Escalar
Operações com um único valor aplicado em um array inteiro

In [69]:
array = np.array([1, 2, 3])

print(array + 2)
print(array * 2)
print(array // 2)

[3 4 5]
[2 4 6]
[0 1 1]

### Funções matemáticas vetorizadas
Aplicar funções em um array inteiro sem usar loop

In [79]:
array = np.array([25.0456, 9.789, 16.546])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))

[5.00455792 3.12873776 4.06767747]
[25. 10. 17.]
[25.  9. 16.]
[26. 10. 17.]

In [82]:
# Exemplo, cálculo de área de círculo

raio = np.array([5, 13.5, 2.8])

area = np.pi * raio ** 2
print(area)

[ 78.53981634 572.55526112  24.6300864 ]

### Element-wise arithmetic
As operações são aplicadas individualmente para cada elemento do array

In [85]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]

### Comparison operators
Criar arrays booleanos, comparar e filtrar dados e compará-los element-wise

In [ ]:
scores = np.array([91, 55, 82, 100, 64, 73])

print(scores == 100)
print(scores <= 60)

# Atribuindo valores para dados que atendem com determinada condição
scores[scores < 60] = 0
print(scores)

[False False False  True False False]
[False  True False False False False]
[ 91   0  82 100  64  73]

### Aggregate functions
Sintetiza a informação e normalmente retorna apenas um valor

In [100]:
print(np.var(scores))
print(np.std(scores))
print(np.min(scores)) 
print(np.argmax(scores)) # index do maior valor
print(np.mean(scores))
print(np.sum(scores))
print(array)
print(np.sum(array, axis=0)) # 0 - colunas, 1 - linhas

1068.888888888889
32.69386622730461
0
3
68.33333333333333
410
[25.0456  9.789  16.546 ]
51.3806

In [110]:
idades = np.array([[18, 13, 25, 15, 28, 35, 16, 19, 27, 33, 92],
         [17, 21, 27, 12, 9, 10, 8, 6, 8, 4, 85]])

teenagers = idades[(idades < 18) & (idades > 12)] # os operadores em NumPy são diferentes por ser baseado em C >> and == &, or == |
adults = idades[idades > 18]
seniors = idades[idades > 65]
par = idades[idades % 2 == 0]
impar = idades[idades % 2 != 0]

print(teenagers)
print(adults)
print(seniors)
print(par)
print(impar)

[13 15 16 17]
[25 28 35 19 27 33 92 21 27 85]
[92 85]
[18 28 16 92 12 10  8  6  8  4]
[13 25 15 35 19 27 33 17 21 27  9 85]

## Pandas
### Series
Pandas trabalha com "Series", as quais são compostas por arrays unidimensionais. Series podem conter diversos tipos de dados, booleano, int, float e str.
Quando criamos uma Series como `series = pd.Series(data)`, `Series` atua como constrututor (S maíusculo) e não como uma função. Series podem ser pensadas como uma coluna / planilha 1D ao invés de um array

In [2]:
import pandas as pd

In [118]:
data = [100, 102, 104, 200, 202]

series = pd.Series(data, index=['a', 'b', 'c', 'd', 'e']) # Se index é nulo, automaticamente é criado um index numérico com início em zero
print(series)

a    100
b    102
c    104
d    200
e    202
dtype: int64

In [120]:
print(series.loc['c']) # a propriedade .loc encontra o valor que possui um determinado label (location by label)

print(series.iloc[2]) # a propriedade .iloc encontra o valor atrelado ao index (location by index)

print(series[series < 200])

104
104
a    100
b    102
c    104
dtype: int64

In [125]:
calories = {
    'Day 1' : 1750,
    'Day 2' : 2100,
    'Day 3' : 1700
}

# Dicionários são compostos de chave-valor, a chave funciona como index em uma Serie 
series = pd.Series(calories)
print(series)
print(series.loc['Day 2'])

series.loc['Day 3'] += 500
print(series.loc['Day 3'])

Day 1    1750
Day 2    2100
Day 3    1700
dtype: int64
2100
2200

In [127]:
print(series[series < 2000])

Day 1    1750
dtype: int64

# DataFrame

In [10]:
data = {
    'Name' : ['Bob Esponja', 'Patrick Estrela', 'Lula Molusco'],
    'Age' : [30, 35, 50]
    }

df = pd.DataFrame(data, index = ['Employee 1', 'Employee 2', 'Employee 3']) # `DataFrame` é um construtor e não uma função, semelhante a `Series`

print(df.loc['Employee 1'])

print(df.iloc[2])

# Como adicionar uma coluna
df['Job'] = ['Cook', 'N/A', 'Cashier'] # o número de dados da coluna precisa ser igual ao número de observações / index 

print(df)

Name    Bob Esponja
Age              30
Name: Employee 1, dtype: object
Name    Lula Molusco
Age               50
Name: Employee 3, dtype: object
                       Name  Age      Job
Employee 1      Bob Esponja   30     Cook
Employee 2  Patrick Estrela   35      N/A
Employee 3     Lula Molusco   50  Cashier

In [17]:
# Como adicionar uma linha

# Esse bloco adiciona uma única linha, é como se fossem preenchidos os valores de cada coluna.
# Para adicionar mais de uma linha, bastaria criar outro dicionário com as respectivas chaves e valores
new_row = pd.DataFrame([{"Name": "Sandy", 'Age': '28', 'Job' : 'Engineer'}],
                        index=['Employee 4']) 

df = pd.concat([df, new_row])
print(df)

                       Name Age       Job
Employee 1      Bob Esponja  30      Cook
Employee 2  Patrick Estrela  35       N/A
Employee 3     Lula Molusco  50   Cashier
Employee 4            Sandy  28  Engineer
Employee 4            Sandy  28  Engineer
Employee 4            Sandy  28  Engineer
Employee 4            Sandy  28  Engineer
Employee 4            Sandy  28  Engineer
Employee 4            Sandy  28  Engineer
Employee 4            Sandy  28  Engineer

In [27]:
df.drop_duplicates(keep='first')

                       Name Age       Job
Employee 1      Bob Esponja  30      Cook
Employee 2  Patrick Estrela  35       N/A
Employee 3     Lula Molusco  50   Cashier
Employee 4            Sandy  28  Engineer

## Importando arquivos

In [64]:
df = pd.read_csv(r'C:\Users\Bruno\Desktop\Python\geo-path\data\raw\df_pkmn.csv', sep=';')
print(df)

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

#### Selecionando dados

In [68]:
#print(df['Height'])
#print(df['Weight'])
#print(df[['Name', 'Height', 'Weight']]) # Quando selecionando mais de uma coluna, precisamos usar uma lista
df.loc[0:3, 'Name']

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
Name: Name, dtype: str

In [11]:
# Com pandas é possível definir os dados de uma coluna como index, por exemplo:

df = pd.read_csv(r'C:\Users\Bruno\Desktop\Python\geo-path\data\raw\df_pkmn.csv', sep=';', index_col='Name')

df.loc['Blastoise']
df.loc['Charizard':'Pikachu', ['Height', 'Weight']]

            Height  Weight
Name
Charizard      1.7    90.5
Squirtle       0.5     9.0
Wartortle      1.0    22.5
Blastoise      1.6    85.5
Caterpie       0.3     2.9
Metapod        0.7     9.9
Butterfree     1.1    32.0
Weedle         0.3     3.2
Kakuna         0.6    10.0
Beedrill       1.0    29.5
Pidgey         0.3     1.8
Pidgeotto      1.1    30.0
Pidgeot        1.5    39.5
Rattata        0.3     3.5
Raticate       0.7    18.5
Spearow        0.3     2.0
Fearow         1.2    38.0
Ekans          2.0     6.9
Arbok          3.5    65.0
Pikachu        0.4     6.0

## Filtros

In [14]:
# tall_pokemon = df[df['Height'] >= 2]
heavy_pokemon = df[df['Weight'] >= 100]

print(heavy_pokemon)

            No     Type1    Type2  Height  Weight  Legendary
Name
Venusaur     3     Grass   Poison     2.0   100.0          0
Arcanine    59      Fire      NaN     1.9   155.0          0
Machamp     68  Fighting      NaN     1.6   130.0          0
Graveler    75      Rock   Ground     1.0   105.0          0
Golem       76      Rock   Ground     1.4   300.0          0
Dewgong     87     Water      Ice     1.7   120.0          0
Cloyster    91     Water      Ice     1.5   132.5          0
Onix        95      Rock   Ground     8.8   210.0          0
Exeggutor  103     Grass  Psychic     2.0   120.0          0
Rhyhorn    111    Ground     Rock     1.0   115.0          0
Rhydon     112    Ground     Rock     1.9   120.0          0
Gyarados   130     Water   Flying     6.5   235.0          0
Lapras     131     Water      Ice     2.5   220.0          0
Snorlax    143    Normal      NaN     2.1   460.0          0
Dragonite  149    Dragon   Flying     2.2   210.0          0
Mewtwo     150   Psychic      NaN     2.0   122.0          1

In [22]:
# legendary_pokemon = df[df['Legendary'] == 1]
# print(legendary_pokemon)

# water_pokemon = df[(df['Type1'] == 'Water') | 
#                    (df['Type2'] == 'Water')]

           No     Type1   Type2  Height  Weight  Legendary
Name
Articuno  144       Ice  Flying     1.7    55.4          1
Zapdos    145  Electric  Flying     1.6    52.6          1
Moltres   146      Fire  Flying     2.0    60.0          1
Mewtwo    150   Psychic     NaN     2.0   122.0          1
             No  Type1     Type2  Height  Weight  Legendary
Name
Squirtle      7  Water       NaN     0.5     9.0          0
Wartortle     8  Water       NaN     1.0    22.5          0
Blastoise     9  Water       NaN     1.6    85.5          0
Psyduck      54  Water       NaN     0.8    19.6          0
Golduck      55  Water       NaN     1.7    76.6          0
Poliwag      60  Water       NaN     0.6    12.4          0
Poliwhirl    61  Water       NaN     1.0    20.0          0
Poliwrath    62  Water  Fighting     1.3    54.0          0
Tentacool    72  Water    Poison     0.9    45.5          0
Tentacruel   73  Water    Poison     1.6    55.0          0
Slowpoke     79  Water   Psychic     1.2    36.0          0
Slowbro      80  Water   Psychic     1.6    78.5          0
Seel         86  Water       NaN     1.1    90.0          0
Dewgong      87  Water       Ice     1.7   120.0          0
Shellder     90  Water       NaN     0.3     4.0          0
Cloyster     91  Water       Ice     1.5   132.5          0
Krabby       98  Water       NaN     0.4     6.5          0
Kingler      99  Water       NaN     1.3    60.0          0
Horsea      116  Water       NaN     0.4     8.0          0
Seadra      117  Water       NaN     1.2    25.0          0
Goldeen     118  Water       NaN     0.6    15.0          0
Seaking     119  Water       NaN     1.3    39.0          0
Staryu      120  Water       NaN     0.8    34.5          0
Starmie     121  Water   Psychic     1.1    80.0          0
Magikarp    129  Water       NaN     0.9    10.0          0
Gyarados    130  Water    Flying     6.5   235.0          0
Lapras      131  Water       Ice     2.5   220.0          0
Vaporeon    134  Water       NaN     1.0    29.0          0
Omanyte     138   Rock     Water     0.4     7.5          0
Omastar     139   Rock     Water     1.0    35.0          0
Kabuto      140   Rock     Water     0.5    11.5          0
Kabutops    141   Rock     Water     1.3    40.5          0

## Aggregate
Essa função normalmente é utilizada para sumarizar e analisar dados

In [35]:
# Whole dataframe

# print(df.mean(numeric_only=True)) 
# print(df.sum(numeric_only=True))
# print(df.max(numeric_only=True))
# print(df.count())

# sem o kwarg 'numeric_only', seria necessário especificar uma coluna numérica


# Single column

print(df['Type2'].count())

# print(df[df['Height'] == df['Height'].max()])
# print(df[df['Weight'] == df['Weight'].max()])

      No Type1   Type2  Height  Weight  Legendary
Name
Onix  95  Rock  Ground     8.8   210.0          0
          No   Type1 Type2  Height  Weight  Legendary
Name
Snorlax  143  Normal   NaN     2.1   460.0          0
67

## Groupby
Agrupa o data frame com base em informações em comum. <br>
Quando executamos o seguinte código `grupo = df.groupby('Type1')` o resultado é um objeto, e não um resultado que possa ser exibido na tela, conforme exemplo abaixo

In [38]:
grupo = df.groupby('Type1')
print(grupo)

<pandas.api.typing.DataFrameGroupBy object at 0x000002C6EF6FAFD0>

Entretanto, operações podem ser realizadas nos grupos contidos no objeto.

In [52]:
# Valor máximo de todos os tipos para cada coluna (não é a soma)
#print(grupo.max(numeric_only=True))

# Observando os dados agregados de apenas uma coluna

# print(grupo['Weight'].mean())
# print(grupo['Weight'].min())
# print(grupo['Weight'].max())
print(grupo['Weight'].count())

Type1
Bug         12
Dragon       3
Electric     9
Fairy        2
Fighting     7
Fire        12
Ghost        3
Grass       12
Ground       8
Ice          2
Normal      22
Poison      14
Psychic      7
Rock         9
Water       28
Name: Weight, dtype: int64

## Data Cleaning
1. Eliminando colunas irrelevantes com a função `drop()`

In [54]:
new_df = df.drop(columns=['Legendary', 'No'])
print(new_df)

              Type1   Type2  Height  Weight
Name
Bulbasaur     Grass  Poison     0.7     6.9
Ivysaur       Grass  Poison     1.0    13.0
Venusaur      Grass  Poison     2.0   100.0
Charmander     Fire     NaN     0.6     8.5
Charmeleon     Fire     NaN     1.1    19.0
...             ...     ...     ...     ...
Moltres        Fire  Flying     2.0    60.0
Dratini      Dragon     NaN     1.8     3.3
Dragonair    Dragon     NaN     4.0    16.5
Dragonite    Dragon  Flying     2.2   210.0
Mewtwo      Psychic     NaN     2.0   122.0

[150 rows x 4 columns]

2. Lidando com dados faltantes

In [ ]:
# new_df = df.dropna(subset=['Type2'])

new_df = df.fillna({'Type2': 'None'}) # preenche os valores faltantes na coluna 'Type2' com o valor designado 'None'
print(new_df.to_string())

             No     Type1     Type2  Height  Weight  Legendary
Name
Bulbasaur     1     Grass    Poison     0.7     6.9          0
Ivysaur       2     Grass    Poison     1.0    13.0          0
Venusaur      3     Grass    Poison     2.0   100.0          0
Charmander    4      Fire      None     0.6     8.5          0
Charmeleon    5      Fire      None     1.1    19.0          0
Charizard     6      Fire    Flying     1.7    90.5          0
Squirtle      7     Water      None     0.5     9.0          0
Wartortle     8     Water      None     1.0    22.5          0
Blastoise     9     Water      None     1.6    85.5          0
Caterpie     10       Bug      None     0.3     2.9          0
Metapod      11       Bug      None     0.7     9.9          0
Butterfree   12       Bug    Flying     1.1    32.0          0
Weedle       13       Bug    Poison     0.3     3.2          0
Kakuna       14       Bug    Poison     0.6    10.0          0
Beedrill     15       Bug    Poison     1.0    29.5          0
Pidgey       16    Normal    Flying     0.3     1.8          0
Pidgeotto    17    Normal    Flying     1.1    30.0          0
Pidgeot      18    Normal    Flying     1.5    39.5          0
Rattata      19    Normal      None     0.3     3.5          0
Raticate     20    Normal      None     0.7    18.5          0
Spearow      21    Normal    Flying     0.3     2.0          0
Fearow       22    Normal    Flying     1.2    38.0          0
Ekans        23    Poison      None     2.0     6.9          0
Arbok        24    Poison      None     3.5    65.0          0
Pikachu      25  Electric      None     0.4     6.0          0
Raichu       26  Electric      None     0.8    30.0          0
Sandshrew    27    Ground      None     0.6    12.0          0
Sandslash    28    Ground      None     1.0    29.5          0
Nidoran♀     29    Poison      None     0.4     7.0          0
Nidorina     30    Poison      None     0.8    20.0          0
Nidoqueen    31    Poison    Ground     1.3    60.0          0
Nidoran♂     32    Poison      None     0.5     9.0          0
Nidorino     33    Poison      None     0.9    19.5          0
Nidoking     34    Poison    Ground     1.4    62.0          0
Clefairy     35     Fairy      None     0.6     7.5          0
Clefable     36     Fairy      None     1.3    40.0          0
Vulpix       37      Fire      None     0.6     9.9          0
Ninetales    38      Fire      None     1.1    19.9          0
Jigglypuff   39    Normal     Fairy     0.5     5.5          0
Wigglytuff   40    Normal     Fairy     1.0    12.0          0
Zubat        41    Poison    Flying     0.8     7.5          0
Golbat       42    Poison    Flying     1.6    55.0          0
Oddish       43     Grass    Poison     0.5     5.4          0
Gloom        44     Grass    Poison     0.8     8.6          0
Vileplume    45     Grass    Poison     1.2    18.6          0
Paras        46       Bug     Grass     0.3     5.4          0
Parasect     47       Bug     Grass     1.0    29.5          0
Venonat      48       Bug    Poison     1.0    30.0          0
Venomoth     49       Bug    Poison     1.5    12.5          0
Diglett      50    Ground      None     0.2     0.8          0
Dugtrio      51    Ground      None     0.7    33.3          0
Meowth       52    Normal      None     0.4     4.2          0
Persian      53    Normal      None     1.0    32.0          0
Psyduck      54     Water      None     0.8    19.6          0
Golduck      55     Water      None     1.7    76.6          0
Mankey       56  Fighting      None     0.5    28.0          0
Primeape     57  Fighting      None     1.0    32.0          0
Growlithe    58      Fire      None     0.7    19.0          0
Arcanine     59      Fire      None     1.9   155.0          0
Poliwag      60     Water      None     0.6    12.4          0
Poliwhirl    61     Water      None     1.0    20.0          0
Poliwrath    62     Water  Fighting     1.3    54.0          0
Abra         63   Psychic      None     0.9    19.5          0
Kadabra      64   Psychic      None     1.3    56.5          0
Alakazam     65   Psychic      None     1.5    48.0          0
Machop       66  Fighting      None     0.8    19.5          0
Machoke      67  Fighting      None     1.5    70.5          0
Machamp      68  Fighting      None     1.6   130.0          0
Bellsprout   69     Grass    Poison     0.7     4.0          0
Weepinbell   70     Grass    Poison     1.0     6.4          0
Victreebel   71     Grass    Poison     1.7    15.5          0
Tentacool    72     Water    Poison     0.9    45.5          0
Tentacruel   73     Water    Poison     1.6    55.0          0
Geodude      74      Rock    Ground     0.4    20.0          0
Graveler     75      Rock    Ground     1.0   105.0          0
Golem        76      Rock    Ground     1.4   300.0          0
Ponyta       77      Fire      None     1.0    30.0          0
Rapidash     78      Fire      None     1.7    95.0          0
Slowpoke     79     Water   Psychic     1.2    36.0          0
Slowbro      80     Water   Psychic     1.6    78.5          0
Magnemite    81  Electric     Steel     0.3     6.0          0
Magneton     82  Electric     Steel     1.0    60.0          0
Farfetch'd   83    Normal    Flying     0.8    15.0          0
Doduo        84    Normal    Flying     1.4    39.2          0
Dodrio       85    Normal    Flying     1.8    85.2          0
Seel         86     Water      None     1.1    90.0          0
Dewgong      87     Water       Ice     1.7   120.0          0
Grimer       88    Poison      None     0.9    30.0          0
Muk          89    Poison      None     1.2    30.0          0
Shellder     90     Water      None     0.3     4.0          0
Cloyster     91     Water       Ice     1.5   132.5          0
Gastly       92     Ghost    Poison     1.3     0.1          0
Haunter      93     Ghost    Poison     1.6     0.1          0
Gengar       94     Ghost    Poison     1.5    40.5          0
Onix         95      Rock    Ground     8.8   210.0          0
Drowzee      96   Psychic      None     1.0    32.4          0
Hypno        97   Psychic      None     1.6    75.6          0
Krabby       98     Water      None     0.4     6.5          0
Kingler      99     Water      None     1.3    60.0          0
Voltorb     100  Electric      None     0.5    10.4          0
Electrode   101  Electric      None     1.2    66.6          0
Exeggcute   102     Grass   Psychic     0.4     2.5          0
Exeggutor   103     Grass   Psychic     2.0   120.0          0
Cubone      104    Ground      None     0.4     6.5          0
Marowak     105    Ground      None     1.0    45.0          0
Hitmonlee   106  Fighting      None     1.5    49.8          0
Hitmonchan  107  Fighting      None     1.4    50.2          0
Lickitung   108    Normal      None     1.2    65.5          0
Koffing     109    Poison      None     0.6     1.0          0
Weezing     110    Poison      None     1.2     9.5          0
Rhyhorn     111    Ground      Rock     1.0   115.0          0
Rhydon      112    Ground      Rock     1.9   120.0          0
Chansey     113    Normal      None     1.1    34.6          0
Tangela     114     Grass      None     1.0    35.0          0
Kangaskhan  115    Normal      None     2.2    80.0          0
Horsea      116     Water      None     0.4     8.0          0
Seadra      117     Water      None     1.2    25.0          0
Goldeen     118     Water      None     0.6    15.0          0
Seaking     119     Water      None     1.3    39.0          0
Staryu      120     Water      None     0.8    34.5          0
Starmie     121     Water   Psychic     1.1    80.0          0
Mr. Mime    122   Psychic     Fairy     1.3    54.5          0
Scyther     123       Bug    Flying     1.5    56.0          0
Jynx        124       Ice   Psychic     1.4    40.6          0
Electabuzz  125  Electric      None     1.1    30.0          0
Magmar      126      Fire      None     1.3    44.5          0
Pinsir      127       Bug      None     1.5    55.0          0
Tauros      128    Normal      None     1.4    88.4          0
Magikarp    129     Water      None     0.9    10.0          0
Gyarados    130     Water    Flying     6.5   235.0          0
Lapras      131     Water       Ice     2.5   220.0          0
Ditto       132    Normal      None     0.3     4.0          0
Eevee       133    Normal      None     0.3     6.5          0
Vaporeon    134     Water      None     1.0    29.0          0
Jolteon     135  Electric      None     0.8    24.5          0
Flareon     136      Fire      None     0.9    25.0          0
Porygon     137    Normal      None     0.8    36.5          0
Omanyte     138      Rock     Water     0.4     7.5          0
Omastar     139      Rock     Water     1.0    35.0          0
Kabuto      140      Rock     Water     0.5    11.5          0
Kabutops    141      Rock     Water     1.3    40.5          0
Aerodactyl  142      Rock    Flying     1.8    59.0          0
Snorlax     143    Normal      None     2.1   460.0          0
Articuno    144       Ice    Flying     1.7    55.4          1
Zapdos      145  Electric    Flying     1.6    52.6          1
Moltres     146      Fire    Flying     2.0    60.0          1
Dratini     147    Dragon      None     1.8     3.3          0
Dragonair   148    Dragon      None     4.0    16.5          0
Dragonite   149    Dragon    Flying     2.2   210.0          0
Mewtwo      150   Psychic      None     2.0   122.0          1

3. Consertando valores inconsistentes

In [60]:
df['Type1'] = df['Type1'].replace({'Grass' : 'GRASS',
                                   'Fire' : 'FIRE',
                                   'Water' : 'WATER' })
print(df)

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    GRASS  Poison     0.7     6.9          0
Ivysaur       2    GRASS  Poison     1.0    13.0          0
Venusaur      3    GRASS  Poison     2.0   100.0          0
Charmander    4     FIRE     NaN     0.6     8.5          0
Charmeleon    5     FIRE     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     FIRE  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

4. Standardize text

In [66]:
df['Name'] = df['Name'].str.lower()

print(df)

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   bulbasaur    Grass  Poison     0.7     6.9          0
1      2     ivysaur    Grass  Poison     1.0    13.0          0
2      3    venusaur    Grass  Poison     2.0   100.0          0
3      4  charmander     Fire     NaN     0.6     8.5          0
4      5  charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     moltres     Fire  Flying     2.0    60.0          1
146  147     dratini   Dragon     NaN     1.8     3.3          0
147  148   dragonair   Dragon     NaN     4.0    16.5          0
148  149   dragonite   Dragon  Flying     2.2   210.0          0
149  150      mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

5. Fix data types

In [ ]:
# A função astype() quando aplicada pode alterar o tipo de dado de uma coluna
df['Legendary'] = df['Legendary'].astype(bool)
print(df)

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   bulbasaur    Grass  Poison     0.7     6.9      False
1      2     ivysaur    Grass  Poison     1.0    13.0      False
2      3    venusaur    Grass  Poison     2.0   100.0      False
3      4  charmander     Fire     NaN     0.6     8.5      False
4      5  charmeleon     Fire     NaN     1.1    19.0      False
..   ...         ...      ...     ...     ...     ...        ...
145  146     moltres     Fire  Flying     2.0    60.0       True
146  147     dratini   Dragon     NaN     1.8     3.3      False
147  148   dragonair   Dragon     NaN     4.0    16.5      False
148  149   dragonite   Dragon  Flying     2.2   210.0      False
149  150      mewtwo  Psychic     NaN     2.0   122.0       True

[150 rows x 7 columns]

6. Removendo duplicatas

Podemos utilizar o seguinte `df.drop_duplicates(keep='first')`, assim como feito com os dados temáticos de Bob Esponja.